#ifndef __DT_DWC2_LOONGSON_FIX_H
#define __DT_DWC2_LOONGSON_FIX_H

#define DWC2_LOONGSON_FIX_NONE		0
#define DWC2_LOONGSON_FIX_DMA		1
#define DWC2_LOONGSON_FIX_DELAY		2
#define DWC2_LOONGSON_FIX_DELAY_FULL	3

#endif
